# Generated by Django 2.1.2 on 2018-12-14 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentvote',
            name='is_like',
            field=models.BooleanField(blank=True),
        ),
    ]
