# Generated by Django 2.1.2 on 2018-10-30 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_comment_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='votes',
        ),
    ]
