# Generated by Django 2.1.2 on 2018-11-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0013_auto_20181102_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='AskUser', max_length=30),
            preserve_default=False,
        ),
    ]
